name: Flutter Golden Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golden-tests:
    name: Run Flutter Golden Tests
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.6'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Step 4: Run flutter doctor for debugging purposes
    - name: Run flutter doctor
      run: flutter doctor

    # Step 5: Generate golden files (if needed)
    - name: Generate golden files (optional)
      run: |
        flutter test --update-goldens
